cargo-features = ["edition2021"]

[package]
name = "cryptopals"
version = "0.1.0"
authors = ["David Suilea <david.suilea@gmail.com>"]
edition = "2021"

[dependencies]
rustc-serialize = "0.3"
serde_json = "1.0"
